//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetGore.Db.ClassCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetGore.Db.ClassCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class ColumnMetadata
        ///{
        ///    readonly string _name;
        ///    readonly string _comment;
        ///    readonly string _databaseType;
        ///    readonly object _defaultValue;
        ///    readonly Type _type;
        ///    readonly bool _nullable;
        ///    readonly bool _isPrimaryKey;
        ///    readonly bool _isForeignKey;
        ///
        ///    public string Name { get { return _name; } }
        ///
        ///    public string Comment { get { return _comment; } }
        ///
        ///    public string DatabaseType { get { return _databaseType; } }
        ///
        ///    public object DefaultValue { get { return [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ColumnMetadataCode {
            get {
                return ResourceManager.GetString("ColumnMetadataCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// {summary}
        ////// A Dictionary-like lookup table for the Enum values of the type collection `[COLUMNCOLLECTIONNAME]` for the
        ////// table that this class represents. Majority of the code for this class was automatically generated and
        ////// only other automatically generated code should be using this class.
        ////// {/summary}
        ///private class [CLASSNAME]
        ///{
        ///    /// {summary}
        ///    /// Array containing the actual values. The index of this array is found through the value returned
        ///    /// from the _lookupTable.
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConstEnumDictionaryCode {
            get {
                return ResourceManager.GetString("ConstEnumDictionaryCode", resourceCulture);
            }
        }
    }
}
