//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetGore.Db {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DbResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DbResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetGore.Db.DbResources", typeof(DbResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// Contains the metadata for a database column.
        ////// &lt;/summary&gt;
        ///public class ColumnMetadata
        ///{
        ///    /// &lt;summary&gt;
        ///    /// The comment of the column from the database.
        ///    /// &lt;/summary&gt;
        ///    readonly string _comment;
        ///
        ///    /// &lt;summary&gt;
        ///    /// A string containing the database column type.
        ///    /// &lt;/summary&gt;
        ///    readonly string _databaseType;
        ///
        ///    /// &lt;summary&gt;
        ///    /// The default value of the database column. Can be null.
        ///    /// &lt;/summary&gt;
        ///    readonly object _defaultValue;
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ColumnMetadataCode {
            get {
                return ResourceManager.GetString("ColumnMetadataCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// A Dictionary-like lookup table for the Enum values of the type collection `[COLUMNCOLLECTIONNAME]` for the
        ////// table that this class represents. Majority of the code for this class was automatically generated and
        ////// only other automatically generated code should be using this class.
        ////// &lt;/summary&gt;
        ///public class [CLASSNAME] : System.Collections.Generic.IEnumerable&lt;System.Collections.Generic.KeyValuePair&lt;[KEYTYPE], [EXVALUETYPE]&gt;&gt;, IPersistable
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Name of the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConstEnumDictionaryCode {
            get {
                return ResourceManager.GetString("ConstEnumDictionaryCode", resourceCulture);
            }
        }
    }
}
