//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySql.Data.MySqlClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySql.Data.MySqlClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improper MySqlCommandBuilder state: adapter is null.
        /// </summary>
        public static string AdapterIsNull {
            get {
                return ResourceManager.GetString("AdapterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improper MySqlCommandBuilder state: adapter&apos;s SelectCommand is null.
        /// </summary>
        public static string AdapterSelectIsNull {
            get {
                return ResourceManager.GetString("AdapterSelectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version string not in acceptable format.
        /// </summary>
        public static string BadVersionFormat {
            get {
                return ResourceManager.GetString("BadVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The buffer cannot be null.
        /// </summary>
        public static string BufferCannotBeNull {
            get {
                return ResourceManager.GetString("BufferCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Buffer is not large enough.
        /// </summary>
        public static string BufferNotLargeEnough {
            get {
                return ResourceManager.GetString("BufferNotLargeEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling an executing query requires MySQL 5.0 or higher..
        /// </summary>
        public static string CancelNeeds50 {
            get {
                return ResourceManager.GetString("CancelNeeds50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling an active query is only supported on MySQL 5.0.0 and above. .
        /// </summary>
        public static string CancelNotSupported {
            get {
                return ResourceManager.GetString("CancelNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySqlCommandBuilder does not support multi-table statements.
        /// </summary>
        public static string CBMultiTableNotSupported {
            get {
                return ResourceManager.GetString("CBMultiTableNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySqlCommandBuilder cannot operate on tables with no unique or key columns.
        /// </summary>
        public static string CBNoKeyColumn {
            get {
                return ResourceManager.GetString("CBNoKeyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos isolation level is not supported.
        /// </summary>
        public static string ChaosNotSupported {
            get {
                return ResourceManager.GetString("ChaosNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CommandText property has not been properly initialized..
        /// </summary>
        public static string CommandTextNotInitialized {
            get {
                return ResourceManager.GetString("CommandTextNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection is already open..
        /// </summary>
        public static string ConnectionAlreadyOpen {
            get {
                return ResourceManager.GetString("ConnectionAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection unexpectedly terminated..
        /// </summary>
        public static string ConnectionBroken {
            get {
                return ResourceManager.GetString("ConnectionBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection must be valid and open.
        /// </summary>
        public static string ConnectionMustBeOpen {
            get {
                return ResourceManager.GetString("ConnectionMustBeOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection is not open..
        /// </summary>
        public static string ConnectionNotOpen {
            get {
                return ResourceManager.GetString("ConnectionNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection property has not been set or is null..
        /// </summary>
        public static string ConnectionNotSet {
            get {
                return ResourceManager.GetString("ConnectionNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Count cannot be negative.
        /// </summary>
        public static string CountCannotBeNegative {
            get {
                return ResourceManager.GetString("CountCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetLength is not a valid operation on CompressedStream.
        /// </summary>
        public static string CSNoSetLength {
            get {
                return ResourceManager.GetString("CSNoSetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an open DataReader associated with this Connection which must be closed first..
        /// </summary>
        public static string DataReaderOpen {
            get {
                return ResourceManager.GetString("DataReaderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL Connector/Net does not currently support distributed transactions..
        /// </summary>
        public static string DistributedTxnNotSupported {
            get {
                return ResourceManager.GetString("DistributedTxnNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating socket connection.
        /// </summary>
        public static string ErrorCreatingSocket {
            get {
                return ResourceManager.GetString("ErrorCreatingSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error encountered during command execution..
        /// </summary>
        public static string FatalErrorDuringExecute {
            get {
                return ResourceManager.GetString("FatalErrorDuringExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error encountered during data read..
        /// </summary>
        public static string FatalErrorDuringRead {
            get {
                return ResourceManager.GetString("FatalErrorDuringRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error encountered attempting to read the resultset..
        /// </summary>
        public static string FatalErrorReadingResult {
            get {
                return ResourceManager.GetString("FatalErrorReadingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From index and length use more bytes than from contains.
        /// </summary>
        public static string FromAndLengthTooBig {
            get {
                return ResourceManager.GetString("FromAndLengthTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From index must be a valid index inside the from buffer.
        /// </summary>
        public static string FromIndexMustBeValid {
            get {
                return ResourceManager.GetString("FromIndexMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving procedure metadata for {0} from server..
        /// </summary>
        public static string HardProcQuery {
            get {
                return ResourceManager.GetString("HardProcQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value has an unsupported format..
        /// </summary>
        public static string ImproperValueFormat {
            get {
                return ResourceManager.GetString("ImproperValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An incorrect response was received from the server..
        /// </summary>
        public static string IncorrectTransmission {
            get {
                return ResourceManager.GetString("IncorrectTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index and length use more bytes than to has room for.
        /// </summary>
        public static string IndexAndLengthTooBig {
            get {
                return ResourceManager.GetString("IndexAndLengthTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index must be a valid position in the buffer.
        /// </summary>
        public static string IndexMustBeValid {
            get {
                return ResourceManager.GetString("IndexMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure or function &apos;{0}&apos; cannot be found in database &apos;{1}&apos;..
        /// </summary>
        public static string InvalidProcName {
            get {
                return ResourceManager.GetString("InvalidProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword does not allow null values..
        /// </summary>
        public static string KeywordNoNull {
            get {
                return ResourceManager.GetString("KeywordNoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword not supported..
        /// </summary>
        public static string KeywordNotSupported {
            get {
                return ResourceManager.GetString("KeywordNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When MySqlCommandBuilder.ReturnGeneratedIdentifiers is true, MySqlCommand.UpdatedRowSource must be set to None..
        /// </summary>
        public static string MixingUpdatedRowSource {
            get {
                return ResourceManager.GetString("MixingUpdatedRowSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple simultaneous connections or connections with different connection strings inside the same transaction are not currently supported..
        /// </summary>
        public static string MultipleConnectionsInTransactionNotSupported {
            get {
                return ResourceManager.GetString("MultipleConnectionsInTransactionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NamedPipeStream does not support seeking.
        /// </summary>
        public static string NamedPipeNoSeek {
            get {
                return ResourceManager.GetString("NamedPipeNoSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NamedPipeStream doesn&apos;t support SetLength.
        /// </summary>
        public static string NamedPipeNoSetLength {
            get {
                return ResourceManager.GetString("NamedPipeNoSetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid attempt to call NextResult when the reader is closed..
        /// </summary>
        public static string NextResultIsClosed {
            get {
                return ResourceManager.GetString("NextResultIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When calling stored procedures and &apos;Use Procedure Bodies&apos; is false, all parameters must have their type explicitly set..
        /// </summary>
        public static string NoBodiesAndTypeNotSet {
            get {
                return ResourceManager.GetString("NoBodiesAndTypeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested transactions are not supported..
        /// </summary>
        public static string NoNestedTransactions {
            get {
                return ResourceManager.GetString("NoNestedTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object is not open or has been disposed..
        /// </summary>
        public static string ObjectDisposed {
            get {
                return ResourceManager.GetString("ObjectDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Offset cannot be negative.
        /// </summary>
        public static string OffsetCannotBeNegative {
            get {
                return ResourceManager.GetString("OffsetCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset must be a valid position in buffer.
        /// </summary>
        public static string OffsetMustBeValid {
            get {
                return ResourceManager.GetString("OffsetMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; has already been defined..
        /// </summary>
        public static string ParameterAlreadyDefined {
            get {
                return ResourceManager.GetString("ParameterAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot have a negative value.
        /// </summary>
        public static string ParameterCannotBeNegative {
            get {
                return ResourceManager.GetString("ParameterCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot be null.
        /// </summary>
        public static string ParameterCannotBeNull {
            get {
                return ResourceManager.GetString("ParameterCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is invalid..
        /// </summary>
        public static string ParameterIsInvalid {
            get {
                return ResourceManager.GetString("ParameterIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; must be defined..
        /// </summary>
        public static string ParameterMustBeDefined {
            get {
                return ResourceManager.GetString("ParameterMustBeDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be valid and contain length characters.
        /// </summary>
        public static string PasswordMustHaveLegalChars {
            get {
                return ResourceManager.GetString("PasswordMustHaveLegalChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category includes a series of counters for MySQL..
        /// </summary>
        public static string PerfMonCategoryHelp {
            get {
                return ResourceManager.GetString("PerfMonCategoryHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Data Provider for MySQL.
        /// </summary>
        public static string PerfMonCategoryName {
            get {
                return ResourceManager.GetString("PerfMonCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of times a procedures metadata had to be queried from the server..
        /// </summary>
        public static string PerfMonHardProcHelp {
            get {
                return ResourceManager.GetString("PerfMonHardProcHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Procedure Queries.
        /// </summary>
        public static string PerfMonHardProcName {
            get {
                return ResourceManager.GetString("PerfMonHardProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of times a procedures metadata was retrieved from the client-side cache..
        /// </summary>
        public static string PerfMonSoftProcHelp {
            get {
                return ResourceManager.GetString("PerfMonSoftProcHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft Procedure Queries.
        /// </summary>
        public static string PerfMonSoftProcName {
            get {
                return ResourceManager.GetString("PerfMonSoftProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to same name are not supported..
        /// </summary>
        public static string ProcAndFuncSameName {
            get {
                return ResourceManager.GetString("ProcAndFuncSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packets larger than max_allowed_packet are not allowed..
        /// </summary>
        public static string QueryTooLarge {
            get {
                return ResourceManager.GetString("QueryTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading from the stream has failed..
        /// </summary>
        public static string ReadFromStreamFailed {
            get {
                return ResourceManager.GetString("ReadFromStreamFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket streams do not support seeking.
        /// </summary>
        public static string SocketNoSeek {
            get {
                return ResourceManager.GetString("SocketNoSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving procedure metadata for {0} from procedure cache..
        /// </summary>
        public static string SoftProcQuery {
            get {
                return ResourceManager.GetString("SoftProcQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored procedures are not supported on this version of MySQL.
        /// </summary>
        public static string SPNotSupported {
            get {
                return ResourceManager.GetString("SPNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream has already been closed.
        /// </summary>
        public static string StreamAlreadyClosed {
            get {
                return ResourceManager.GetString("StreamAlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The stream does not support reading.
        /// </summary>
        public static string StreamNoRead {
            get {
                return ResourceManager.GetString("StreamNoRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream does not support writing.
        /// </summary>
        public static string StreamNoWrite {
            get {
                return ResourceManager.GetString("StreamNoWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding..
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error connecting: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached..
        /// </summary>
        public static string TimeoutGettingConnection {
            get {
                return ResourceManager.GetString("TimeoutGettingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to any of the specified MySQL hosts..
        /// </summary>
        public static string UnableToConnectToHost {
            get {
                return ResourceManager.GetString("UnableToConnectToHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute stored procedure &apos;{0}&apos;..
        /// </summary>
        public static string UnableToExecuteSP {
            get {
                return ResourceManager.GetString("UnableToExecuteSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error parsing the foreign key definition..
        /// </summary>
        public static string UnableToParseFK {
            get {
                return ResourceManager.GetString("UnableToParseFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve stored procedure metadata.  Either grant  SELECT privilege to mysql.proc for this user or use &quot;use procedure bodies=false&quot; with  your connection string..
        /// </summary>
        public static string UnableToRetrieveSProcData {
            get {
                return ResourceManager.GetString("UnableToRetrieveSProcData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unix sockets are not supported on Windows.
        /// </summary>
        public static string UnixSocketsNotSupported {
            get {
                return ResourceManager.GetString("UnixSocketsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing to the stream failed..
        /// </summary>
        public static string WriteToStreamFailed {
            get {
                return ResourceManager.GetString("WriteToStreamFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is not found but a parameter with the name &apos;{1}&apos; is found. Parameter names must include the leading parameter marker..
        /// </summary>
        public static string WrongParameterName {
            get {
                return ResourceManager.GetString("WrongParameterName", resourceCulture);
            }
        }
    }
}
