//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetGore.IO.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetGore.IO.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Bodies&gt;
        ///	&lt;Body Index=&quot;1&quot;&gt;
        ///		&lt;Size Width=&quot;30&quot; Height=&quot;78&quot; /&gt;
        ///		&lt;Body SkelBody=&quot;basic&quot; /&gt;
        ///		&lt;Stand SkelSet=&quot;stand&quot; /&gt;
        ///		&lt;Walk SkelSet=&quot;walk&quot; /&gt;
        ///		&lt;Jump SkelSet=&quot;jump&quot; /&gt;
        ///		&lt;Fall SkelSet=&quot;fall&quot; /&gt;
        ///		
        ///		&lt;Punch SkelSet=&quot;punch&quot; X=&quot;$width/2&quot; Y=&quot;0&quot; Width=&quot;$width&quot; Height=&quot;$height/2&quot; /&gt;
        ///	&lt;/Body&gt;
        ///	&lt;Body Index=&quot;2&quot;&gt;
        ///		&lt;Size Width=&quot;300&quot; Height=&quot;78&quot; /&gt;
        ///		&lt;Body SkelBody=&quot;aa&quot; /&gt;
        ///		&lt;Stand SkelSet=&quot;b&quot; /&gt;
        ///		&lt;Walk SkelSet=&quot;c&quot; /&gt;
        ///		&lt;Jump SkelSet=&quot;dd&quot; /&gt;
        ///		&lt;Fall SkelSet=&quot;e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasicXmlFile {
            get {
                return ResourceManager.GetString("BasicXmlFile", resourceCulture);
            }
        }
    }
}
