//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoGame.Editor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class EditorSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static EditorSettings defaultInstance = ((EditorSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EditorSettings())));
        
        public static EditorSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::System.Windows.Forms.Keys Screen_ScrollLeft {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Screen_ScrollLeft"]));
            }
            set {
                this["Screen_ScrollLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public global::System.Windows.Forms.Keys Screen_ScrollRight {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Screen_ScrollRight"]));
            }
            set {
                this["Screen_ScrollRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Up")]
        public global::System.Windows.Forms.Keys Screen_ScrollUp {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Screen_ScrollUp"]));
            }
            set {
                this["Screen_ScrollUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Down")]
        public global::System.Windows.Forms.Keys Screen_ScrollDown {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Screen_ScrollDown"]));
            }
            set {
                this["Screen_ScrollDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public float Screen_ScrollPixelsPerSec {
            get {
                return ((float)(this["Screen_ScrollPixelsPerSec"]));
            }
            set {
                this["Screen_ScrollPixelsPerSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MapGrh_DefaultIsForeground {
            get {
                return ((bool)(this["MapGrh_DefaultIsForeground"]));
            }
            set {
                this["MapGrh_DefaultIsForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short MapGrh_DefaultDepth {
            get {
                return ((short)(this["MapGrh_DefaultDepth"]));
            }
            set {
                this["MapGrh_DefaultDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32, 32")]
        public global::SFML.Graphics.Vector2 GridSize {
            get {
                return ((global::SFML.Graphics.Vector2)(this["GridSize"]));
            }
            set {
                this["GridSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2048, 2048")]
        public global::SFML.Graphics.Vector2 MapPreview_TextureSize {
            get {
                return ((global::SFML.Graphics.Vector2)(this["MapPreview_TextureSize"]));
            }
            set {
                this["MapPreview_TextureSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::System.Windows.Forms.Keys Screen_ScrollLeft2 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Screen_ScrollLeft2"]));
            }
            set {
                this["Screen_ScrollLeft2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public global::System.Windows.Forms.Keys Screen_ScrollRight2 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Screen_ScrollRight2"]));
            }
            set {
                this["Screen_ScrollRight2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public global::System.Windows.Forms.Keys Screen_ScrollUp2 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Screen_ScrollUp2"]));
            }
            set {
                this["Screen_ScrollUp2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::System.Windows.Forms.Keys Screen_ScrollDown2 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Screen_ScrollDown2"]));
            }
            set {
                this["Screen_ScrollDown2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InitialMapId {
            get {
                return ((int)(this["InitialMapId"]));
            }
            set {
                this["InitialMapId"] = value;
            }
        }
    }
}
