//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoGame.Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class ClientSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ClientSettings defaultInstance = ((ClientSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ClientSettings())));
        
        public static ClientSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string Network_ServerIP {
            get {
                return ((string)(this["Network_ServerIP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600000")]
        public uint Network_SyncGameTimeFrequency {
            get {
                return ((uint)(this["Network_SyncGameTimeFrequency"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UI_EnteredUserName {
            get {
                return ((string)(this["UI_EnteredUserName"]));
            }
            set {
                this["UI_EnteredUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UI_EnteredPassword {
            get {
                return ((string)(this["UI_EnteredPassword"]));
            }
            set {
                this["UI_EnteredPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::SFML.Window.Keyboard.Key Keys_MoveLeft {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_MoveLeft"]));
            }
            set {
                this["Keys_MoveLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public global::SFML.Window.Keyboard.Key Keys_MoveRight {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_MoveRight"]));
            }
            set {
                this["Keys_MoveRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Up")]
        public global::SFML.Window.Keyboard.Key Keys_MoveUp {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_MoveUp"]));
            }
            set {
                this["Keys_MoveUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Down")]
        public global::SFML.Window.Keyboard.Key Keys_MoveDown {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_MoveDown"]));
            }
            set {
                this["Keys_MoveDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LControl")]
        public global::SFML.Window.Keyboard.Key Keys_Attack {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_Attack"]));
            }
            set {
                this["Keys_Attack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LAlt")]
        public global::SFML.Window.Keyboard.Key Keys_UseWorld {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_UseWorld"]));
            }
            set {
                this["Keys_UseWorld"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LAlt")]
        public global::SFML.Window.Keyboard.Key Keys_UseShop {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_UseShop"]));
            }
            set {
                this["Keys_UseShop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LAlt")]
        public global::SFML.Window.Keyboard.Key Keys_TalkToNPC {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_TalkToNPC"]));
            }
            set {
                this["Keys_TalkToNPC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Space")]
        public global::SFML.Window.Keyboard.Key Keys_PickUp {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_PickUp"]));
            }
            set {
                this["Keys_PickUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Num1")]
        public global::SFML.Window.Keyboard.Key Keys_EmoteEllipsis {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_EmoteEllipsis"]));
            }
            set {
                this["Keys_EmoteEllipsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Num2")]
        public global::SFML.Window.Keyboard.Key Keys_EmoteExclamation {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_EmoteExclamation"]));
            }
            set {
                this["Keys_EmoteExclamation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Num3")]
        public global::SFML.Window.Keyboard.Key Keys_EmoteHeartbroken {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_EmoteHeartbroken"]));
            }
            set {
                this["Keys_EmoteHeartbroken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Num4")]
        public global::SFML.Window.Keyboard.Key Keys_EmoteHearts {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_EmoteHearts"]));
            }
            set {
                this["Keys_EmoteHearts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Num5")]
        public global::SFML.Window.Keyboard.Key Keys_EmoteMeat {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_EmoteMeat"]));
            }
            set {
                this["Keys_EmoteMeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Num6")]
        public global::SFML.Window.Keyboard.Key Keys_EmoteQuestion {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_EmoteQuestion"]));
            }
            set {
                this["Keys_EmoteQuestion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Num7")]
        public global::SFML.Window.Keyboard.Key Keys_EmoteSweat {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_EmoteSweat"]));
            }
            set {
                this["Keys_EmoteSweat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F1")]
        public global::SFML.Window.Keyboard.Key Keys_QuickBarItem0 {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_QuickBarItem0"]));
            }
            set {
                this["Keys_QuickBarItem0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F2")]
        public global::SFML.Window.Keyboard.Key Keys_QuickBarItem1 {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_QuickBarItem1"]));
            }
            set {
                this["Keys_QuickBarItem1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F3")]
        public global::SFML.Window.Keyboard.Key Keys_QuickBarItem2 {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_QuickBarItem2"]));
            }
            set {
                this["Keys_QuickBarItem2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F4")]
        public global::SFML.Window.Keyboard.Key Keys_QuickBarItem3 {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_QuickBarItem3"]));
            }
            set {
                this["Keys_QuickBarItem3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F5")]
        public global::SFML.Window.Keyboard.Key Keys_QuickBarItem4 {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_QuickBarItem4"]));
            }
            set {
                this["Keys_QuickBarItem4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F6")]
        public global::SFML.Window.Keyboard.Key Keys_QuickBarItem5 {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_QuickBarItem5"]));
            }
            set {
                this["Keys_QuickBarItem5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F7")]
        public global::SFML.Window.Keyboard.Key Keys_QuickBarItem6 {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_QuickBarItem6"]));
            }
            set {
                this["Keys_QuickBarItem6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F8")]
        public global::SFML.Window.Keyboard.Key Keys_QuickBarItem7 {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_QuickBarItem7"]));
            }
            set {
                this["Keys_QuickBarItem7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F9")]
        public global::SFML.Window.Keyboard.Key Keys_QuickBarItem8 {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_QuickBarItem8"]));
            }
            set {
                this["Keys_QuickBarItem8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F10")]
        public global::SFML.Window.Keyboard.Key Keys_QuickBarItem9 {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_QuickBarItem9"]));
            }
            set {
                this["Keys_QuickBarItem9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public byte Audio_SoundVolume {
            get {
                return ((byte)(this["Audio_SoundVolume"]));
            }
            set {
                this["Audio_SoundVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public byte Audio_MusicVolume {
            get {
                return ((byte)(this["Audio_MusicVolume"]));
            }
            set {
                this["Audio_MusicVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Graphics_VSync {
            get {
                return ((bool)(this["Graphics_VSync"]));
            }
            set {
                this["Graphics_VSync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UI_RememberPassword {
            get {
                return ((bool)(this["UI_RememberPassword"]));
            }
            set {
                this["UI_RememberPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Graphics_Fullscreen {
            get {
                return ((bool)(this["Graphics_Fullscreen"]));
            }
            set {
                this["Graphics_Fullscreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LControl")]
        public global::SFML.Window.Keyboard.Key Keys_Emote_Modifier1 {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_Emote_Modifier1"]));
            }
            set {
                this["Keys_Emote_Modifier1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unknown")]
        public global::SFML.Window.Keyboard.Key Keys_Emote_Modifier2 {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_Emote_Modifier2"]));
            }
            set {
                this["Keys_Emote_Modifier2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unknown")]
        public global::SFML.Window.Keyboard.Key Keys_QuickBarItem_Modifier1 {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_QuickBarItem_Modifier1"]));
            }
            set {
                this["Keys_QuickBarItem_Modifier1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unknown")]
        public global::SFML.Window.Keyboard.Key Keys_QuickBarItem_Modifier2 {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_QuickBarItem_Modifier2"]));
            }
            set {
                this["Keys_QuickBarItem_Modifier2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::SFML.Window.Keyboard.Key Keys_Window_Stats {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_Window_Stats"]));
            }
            set {
                this["Keys_Window_Stats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public global::SFML.Window.Keyboard.Key Keys_Window_Inventory {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_Window_Inventory"]));
            }
            set {
                this["Keys_Window_Inventory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public global::SFML.Window.Keyboard.Key Keys_Window_Equipped {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_Window_Equipped"]));
            }
            set {
                this["Keys_Window_Equipped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public global::SFML.Window.Keyboard.Key Keys_Window_Guild {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_Window_Guild"]));
            }
            set {
                this["Keys_Window_Guild"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::SFML.Window.Keyboard.Key Keys_Window_Skills {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_Window_Skills"]));
            }
            set {
                this["Keys_Window_Skills"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LControl")]
        public global::SFML.Window.Keyboard.Key Keys_Window_Modifier1 {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_Window_Modifier1"]));
            }
            set {
                this["Keys_Window_Modifier1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unknown")]
        public global::SFML.Window.Keyboard.Key Keys_Window_Modifier2 {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_Window_Modifier2"]));
            }
            set {
                this["Keys_Window_Modifier2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseProfanityFilter {
            get {
                return ((bool)(this["UseProfanityFilter"]));
            }
            set {
                this["UseProfanityFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LShift")]
        public global::SFML.Window.Keyboard.Key Keys_ClickWarp {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_ClickWarp"]));
            }
            set {
                this["Keys_ClickWarp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LControl")]
        public global::SFML.Window.Keyboard.Key Keys_ClickWarp2 {
            get {
                return ((global::SFML.Window.Keyboard.Key)(this["Keys_ClickWarp2"]));
            }
            set {
                this["Keys_ClickWarp2"] = value;
            }
        }
    }
}
