//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoxyPacker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoxyPacker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///function hasClass(ele,cls) {
        ///  return ele.className.match(new RegExp(&apos;(\\s|^)&apos;+cls+&apos;(\\s|$)&apos;));
        ///}
        ///
        ///function addClass(ele,cls) {
        ///  if (!this.hasClass(ele,cls)) ele.className += &quot; &quot;+cls;
        ///}
        ///
        ///function removeClass(ele,cls) {
        ///  if (hasClass(ele,cls)) {
        ///    var reg = new RegExp(&apos;(\\s|^)&apos;+cls+&apos;(\\s|$)&apos;);
        ///    ele.className=ele.className.replace(reg,&apos; &apos;);
        ///  }
        ///}
        ///
        ///function toggleVisibility(linkObj) {
        /// var base = linkObj.getAttribute(&apos;id&apos;);
        /// var summary = document.getElementById(base + &apos;-summary&apos;);
        /// var content = docum [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jscriptToggleVisibility_FileData {
            get {
                return ResourceManager.GetString("jscriptToggleVisibility_FileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.js.
        /// </summary>
        internal static string jscriptToggleVisibility_FileName {
            get {
                return ResourceManager.GetString("jscriptToggleVisibility_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;
        ///function hasClass(ele,cls) {
        ///  return ele.className.match(new RegExp(&apos;(\\s|^)&apos;+cls+&apos;(\\s|$)&apos;));
        ///}
        ///
        ///function addClass(ele,cls) {
        ///  if (!this.hasClass(ele,cls)) ele.className += &quot; &quot;+cls;
        ///}
        ///
        ///function removeClass(ele,cls) {
        ///  if (hasClass(ele,cls)) {
        ///    var reg = new RegExp(&apos;(\\s|^)&apos;+cls+&apos;(\\s|$)&apos;);
        ///    ele.className=ele.className.replace(reg,&apos; &apos;);
        ///  }
        ///}
        ///
        ///function toggleVisibility(linkObj) {
        /// var base = linkObj.getAttribute(&apos;id&apos;);
        /// var summary = document.getElementById(base + &apos;- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jscriptToggleVisiblity_Find {
            get {
                return ResourceManager.GetString("jscriptToggleVisiblity_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javaScript&quot; language=&quot;javascript&quot; src=&quot;v.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        internal static string jscriptToggleVisiblity_Rep {
            get {
                return ResourceManager.GetString("jscriptToggleVisiblity_Rep", resourceCulture);
            }
        }
    }
}
